
let MANIFEST=null, PROVIDERS=[], selectedProvider=null, renderLimit=72, liveSource=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const enc=p=>p.split('/').map((x,i)=>i?encodeURIComponent(x):x).join('/');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const nice=s=>String(s??'').replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/\s+/g,' ').trim();
function abs(path){return new URL(enc(path),location.href).href}
function repoInfo(){const h=location.hostname.toLowerCase(),ps=location.pathname.split('/').filter(Boolean);if(h.endsWith('.github.io')&&ps.length)return{owner:h.replace('.github.io',''),repo:ps[0]};return null}
async function liveTree(){const r=repoInfo();if(!r)return null;const meta=await fetch(`https://api.github.com/repos/${r.owner}/${r.repo}`);if(!meta.ok)throw 0;const mi=await meta.json();const br=mi.default_branch||'main';const tr=await fetch(`https://api.github.com/repos/${r.owner}/${r.repo}/git/trees/${encodeURIComponent(br)}?recursive=1`);if(!tr.ok)throw 0;const tj=await tr.json();const map=new Map();for(const x of tj.tree||[]){if(x.type!=='blob'||!x.path.startsWith('assets/game-providers/'))continue;const rel=x.path.slice('assets/game-providers/'.length);const parts=rel.split('/');if(parts.length<2)continue;const p=parts[0];if(!map.has(p))map.set(p,{name:p,folder:p,logos:[],games:[],count:0});const o=map.get(p);const low=x.path.toLowerCase();if(parts.length===2&&/\.(png|jpg|jpeg|webp|gif|svg|avif)$/.test(low))o.logos.push(x.path);else if(parts[1]==='LIST'&&parts.length>=3&&/\.(png|jpg|jpeg|webp|gif|svg|avif)$/.test(low)){const f=parts.slice(2).join('/');o.games.push({name:f.replace(/\.[^.]+$/,''),file:f.split('/').pop(),path:x.path})}}
const arr=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name));arr.forEach(p=>{p.logos.sort();p.games.sort((a,b)=>a.name.localeCompare(b.name));p.count=p.games.length});return arr}
async function load(){const m=await fetch('data/manifest.json').then(r=>r.json());MANIFEST=m;PROVIDERS=m.providers;renderStats();renderHome();try{const lp=await liveTree();if(lp&&lp.length){PROVIDERS=lp;liveSource=true;renderStats();renderHome()}}catch(e){}}
function renderStats(){$('#statProviders').textContent=PROVIDERS.length.toLocaleString();$('#statGames').textContent=PROVIDERS.reduce((a,p)=>a+p.games.length,0).toLocaleString();$('#statLogos').textContent=PROVIDERS.reduce((a,p)=>a+p.logos.length,0).toLocaleString();$('#sourceLabel').textContent=liveSource?'Live GitHub folder scan':'Packaged manifest'}
function setView(v,updateHash=true){
  const valid=['home','games','banks']; if(!valid.includes(v))v='home';
  $('#homeView').classList.toggle('hidden',v!=='home');
  $('#gameView').classList.toggle('hidden',v!=='games');
  $('#bankView').classList.toggle('hidden',v!=='banks');
  $$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));
  if(v==='games')renderHome();
  if(updateHash){history.replaceState(null,'',v==='home'?location.pathname+location.search:'#'+v)}
  window.scrollTo({top:0,behavior:'smooth'});
}
function renderHome(){selectedProvider=null;renderLimit=72;$('#backBtn').classList.add('hidden');$('#providerLogos').classList.add('hidden');$('#providerLogoTitle').classList.add('hidden');$('#gameSectionTitle').textContent='Providers';$('#resultCount').textContent=`${PROVIDERS.length} providers`;$('#loadMore').classList.add('hidden');const q=$('#searchInput').value.trim().toLowerCase();if(q){renderSearch(q);return}$('#gameGrid').innerHTML='';$('#providerGrid').classList.remove('hidden');$('#providerGrid').innerHTML=PROVIDERS.map(p=>`<article class="provider" data-provider="${esc(p.name)}"><div class="provider-logo">${p.logos[0]?`<img loading="lazy" src="${enc(p.logos[0])}" alt="${esc(p.name)}">`:`<b>${esc(p.name)}</b>`}</div><h4>${esc(p.name)}</h4><small>${p.games.length.toLocaleString()} game images · ${p.logos.length} logo${p.logos.length===1?'':'s'}</small></article>`).join('');$$('.provider').forEach(x=>x.onclick=()=>openProvider(x.dataset.provider))}
function openProvider(name){selectedProvider=PROVIDERS.find(p=>p.name===name);if(!selectedProvider)return;renderLimit=72;$('#searchInput').value='';$('#backBtn').classList.remove('hidden');$('#providerGrid').classList.add('hidden');renderProviderLogos();renderGames(selectedProvider.games)}
function renderProviderLogos(){const p=selectedProvider;$('#providerLogoTitle').classList.remove('hidden');$('#providerLogoTitle h3').textContent=`${p.name} — Provider Logo${p.logos.length===1?'':'s'}`;$('#providerLogos').classList.remove('hidden');$('#providerLogos').innerHTML=p.logos.length?p.logos.map(path=>`<div class="logo-card"><div class="logo-img"><img src="${enc(path)}" alt="${esc(p.name)} logo"></div><div class="filename">${esc(path.split('/').pop())}</div><div class="mini-actions"><button class="mini copy" data-copy="${esc(path)}">Copy URL</button><a class="mini" href="${enc(path)}" target="_blank">Open</a></div></div>`).join(''):'<div class="empty">No provider logo in this folder.</div>';bindCopy()}
function renderSearch(q){$('#providerGrid').classList.add('hidden');$('#providerLogos').classList.add('hidden');$('#providerLogoTitle').classList.add('hidden');const matches=[];for(const p of PROVIDERS){if(p.name.toLowerCase().includes(q)){for(const g of p.games)matches.push({...g,provider:p.name,folder:p.folder})}else{for(const g of p.games)if(g.name.toLowerCase().includes(q))matches.push({...g,provider:p.name,folder:p.folder})}}$('#gameSectionTitle').textContent='Search Results';renderGames(matches)}
function currentMatches(){const q=$('#searchInput').value.trim().toLowerCase();if(!selectedProvider)return[];return selectedProvider.games.filter(g=>!q||g.name.toLowerCase().includes(q))}
function renderGames(items){const p=selectedProvider;const normalized=items.map(g=>g.provider?g:{...g,provider:p.name,folder:p.folder});$('#gameSectionTitle').textContent=p&&!$('#searchInput').value?`${p.name} Games`:'Search Results';$('#resultCount').textContent=`${normalized.length.toLocaleString()} assets`;const shown=normalized.slice(0,renderLimit);$('#gameGrid').innerHTML=shown.length?shown.map(g=>gameCard(g)).join(''):'<div class="empty">No matching game assets.</div>';$('#loadMore').classList.toggle('hidden',shown.length>=normalized.length);bindGameActions()}
function gameCard(g){return `<article class="game"><div class="thumb" data-preview="${esc(g.path)}" data-title="${esc(nice(g.name))}"><img loading="lazy" src="${enc(g.path)}" alt="${esc(nice(g.name))}"></div><div class="gamebody"><div class="gamename" title="${esc(g.name)}">${esc(nice(g.name))}</div><div class="gameprovider">${esc(g.provider)} · ${esc(g.file)}</div><div class="actions"><button class="action copy" data-copy="${esc(g.path)}">Copy URL</button><a class="action" href="${enc(g.path)}" download>Download</a><button class="action tips" data-tip-provider="${esc(g.provider)}" data-tip-file="${esc(g.file)}" data-tip-game="${esc(nice(g.name))}">Game Tips</button></div></div></article>`}
function bindCopy(){$$('.copy').forEach(b=>b.onclick=async()=>{const u=abs(b.dataset.copy);try{await navigator.clipboard.writeText(u);const t=b.textContent;b.textContent='Copied ✓';setTimeout(()=>b.textContent=t,1000)}catch(e){prompt('Copy URL:',u)}})}
function bindGameActions(){bindCopy();$$('[data-preview]').forEach(x=>x.onclick=()=>preview(x.dataset.preview,x.dataset.title));$$('[data-tip-file]').forEach(x=>x.onclick=()=>showTips(x.dataset.tipProvider,x.dataset.tipFile,x.dataset.tipGame))}
function preview(path,title){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=`<img class="previewimg" src="${enc(path)}" alt="${esc(title)}"><div class="mini-actions" style="margin-top:10px"><button class="mini copy" data-copy="${esc(path)}">Copy Image URL</button><a class="mini" href="${enc(path)}" target="_blank">Open Original</a></div>`;$('#modal').classList.add('show');bindCopy()}
async function showTips(provider,file,game){const stem=file.replace(/\.[^.]+$/,'');const path=`assets/game-providers/${provider}/TIPS/${stem}.txt`;$('#modalTitle').textContent=`${game} — Game Tips`;$('#modalBody').innerHTML='<div class="tiptext">Loading tips...</div>';$('#modal').classList.add('show');try{const r=await fetch(enc(path)+'?v='+Date.now());if(!r.ok)throw 0;const t=await r.text();$('#modalBody').innerHTML=`<div class="tiptext">${esc(t)}</div><div class="tiphelp">Published from <code>${esc(path)}</code></div>`}catch(e){$('#modalBody').innerHTML=`<div class="tiptext">No tips published yet.</div><div class="tiphelp">To add tips for this game, create this text file in GitHub:<br><br><code>${esc(path)}</code><br><br>The TXT filename must match the game image filename.</div>`}}
$('#modalClose').onclick=()=>$('#modal').classList.remove('show');
$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};
$('#searchInput').addEventListener('input',()=>{renderLimit=72;if(selectedProvider)renderGames(currentMatches());else renderHome()});
$('#clearSearch').onclick=()=>{$('#searchInput').value='';selectedProvider?renderGames(selectedProvider.games):renderHome()};
$('#backBtn').onclick=()=>{$('#searchInput').value='';renderHome()};
$('#loadMore').onclick=()=>{renderLimit+=72;if(selectedProvider)renderGames(currentMatches());else renderSearch($('#searchInput').value.trim().toLowerCase())};
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$$('[data-open-view]').forEach(b=>b.onclick=()=>setView(b.dataset.openView));
window.addEventListener('hashchange',()=>setView(location.hash==='#banks'?'banks':location.hash==='#games'?'games':'home',false));
load().then(()=>setView(location.hash==='#banks'?'banks':location.hash==='#games'?'games':'home',false));
